title: Sean Orfila
description: Hi 👋 Welcome to my website & portfolio. I'm a Frontend Web Developer from CA.
keywords: Front-end developer, UI/UX Design, Shopify Developer
author: Sean Orfila
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sean-orfila.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-sitemap